# @file mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
modLoader="javafml" # forge FML java
loaderVersion="[25,)"
issueTrackerURL="https://github.com/stfwi/engineers-tools/issues/"

[[mods]]
modId="engineerstools"
version="${file.jarVersion}"
displayName="Engineer's Tools"
description="Adds manual handheld tools for the Engineer."
authors="wilechaote"
credits="BluSunrize, malte, Vazkii, Ellpeck, the Forge Smiths, the modders of the world."
updateJSONURL="https://raw.githubusercontent.com/stfwi/engineers-tools/develop/meta/update.json"
displayURL="https://github.com/stfwi/engineers-tools/"
logoFile="logo.png"

[[dependencies.engineerstools]]
  modId="forge"
  mandatory=true
  versionRange="[30,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.engineerstools]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.15.1]"
  ordering="NONE"
  side="BOTH"
